name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t memberservice:latest .

      # (Opcional) Publicar la imagen en Docker Hub para que Render la use
      # - name: Log in to Docker Hub
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      # - name: Tag and push image
      #   run: |
      #     docker tag memberservice:latest yourusername/memberservice:latest
      #     docker push yourusername/memberservice:latest

      # (Opcional) Trigger a redeploy via Render API
      # - name: Trigger Render Deploy
      #   run: |
      #     curl -X POST https://api.render.com/v1/deploy/srv-<your_service_id>/deploys \
      #          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
      #          -H "Content-Type: application/json" \
      #          -d '{}'
